### ISSUE TITLE
[Feature] Provide a one-shot "upgrade only" mode?

### ISSUE THREAD

**Issue by Ezwen** [pgautoupgrade/docker-pgautoupgrade#13]
Currently this image is supposed to be used as a drop-in replacement for the official postgres image, with the extra auto-upgrade feature on top of it.

However, I would assume some people would still prefer to stick using the official postgres image as much as possible, but would still be interested in the upgrading procedure embedded in this image.

To be able to combine both worlds: could we imagine using this image _just_ for upgrading, using a dedicated flag? For instance with such flag we would check the version, perform an upgrade if required, and just exit. Then after that one could continue using the official postgres image once the upgrade is done.

**Comment by justinclift** [comment]
It would be possible to implement, but it's not a high priority.

If someone *really* wants to use this just for the upgrade portion of things then they can already do so.

They just need to switch to this image + start it up.

When the database comes online, that means the upgrade is done.  At that point, they can shut down the database and switch to their desired "official" postgresql docker image and things should work fine.

In theory. :grin:

**Comment by Ezwen** [comment]
> It would be possible to implement, but it's not a high priority.

I understand, better to keep the project focused.

> When the database comes online, that means the upgrade is done. At that point, they can shut down the database and switch to their desired "official" postgresql docker image and things should work fine.

Yes that's what I had in mind. I'll try do achieve this on my own, and report here if it works out OK :)

Thanks!

**Comment by justinclift** [comment]
> I'll try do achieve this on my own, and report here if it works out OK :)

@Ezwen Did you have a chance to try it out? :smile:

**Comment by justinclift** [comment]
Just added this "one shot" capability (https://github.com/pgautoupgrade/docker-pgautoupgrade/commit/d50f8c9234eb972c863df85e8e32bc9e2ddf2a02).

To use it, add a new environment variable `PGAUTO_ONESHOT` (set to `yes`) in the container when pgautoupgrade runs.

When it sees that environment variable, it'll exit after doing the upgrade instead of starting a PostgreSQL server.

New Docker images have been generated and pushed to Docker Hub.

If anyone wants to try it out and report back any weirdness (shouldn't be any though), that'd be cool. :smile:
